### ISSUE TITLE
Feedback F13 (issue 1, CM): Empty "RML_Modules" sheet

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#350]
The Resources and RML_Modules sheets are empty.

**Comment by csnyulas** [comment]
This was fixed (as part of the the TX1.4 delivery, I think). Current RML_Modules sheet is definitely not empty.

![image](https://user-images.githubusercontent.com/2441046/235656277-dedc6593-023e-4e4b-8fd6-5cdab4671f99.png)

**Comment by muricna** [comment]
The TX1-4 delivery was used for validating so it seems it is still a problem

**Comment by muricna** [comment]
My mistake you are correct
